export const SET_ENTRIES = 'SET_ENTRIES'
export const LOGIN = 'LOGIN'
export const SET_DATE = 'SET_DATE'
export const SET_FILTER = 'SET_FILTER'
export const SET_ENTRY = 'SET_ENTRY'
export const CLEAN_SELECTED = 'CLEAN_SELECTED'
export const CREATE_ENTRY = 'CREATE_ENTRY'
export const UPDATE_SEARCH = 'UPDATE_SEARCH'

export const SET_SETTINGS_SCHEMAS = 'SET_SETTINGS_SCHEMAS'
export const SET_PROJECT_CONFIG = 'SET_PROJECT_CONFIG'
export const SET_PROJECT_ID = 'SET_PROJECT_ID'

export const UPDATE_PROPERTY = 'UPDATE_PROPERTY'
