export const SET_ENTRIES = 'SET_ENTRIES'
export const LOGIN = 'LOGIN'
export const SET_DATE = 'SET_DATE'
export const SET_FILTER = 'SET_FILTER'
export const SET_ENTRY = 'SET_ENTRY'
export const CLEAN_SELECTED = 'CLEAN_SELECTED'
